version: "3.9"

services:
  app:
    build: .
    container_name: blog_nest_app_container
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: 8000
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/blog_next?schema=public
    ports:
      - "8000:8000"

  postgres:
    image: postgres:14
    container_name: blog_database_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: blog_next
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
